/* =============================================================================
   004_create_file_formats_stages.sql
   snowflake-claims-platform :: File formats & INTERNAL stages
   -----------------------------------------------------------------------------
   HARD CONSTRAINT: 100% Snowflake-only. INTERNAL named stages ONLY.
   NO S3 / Azure Blob / GCS / external stages / storage integrations anywhere.
   Files are pushed to internal stages with PUT and loaded with COPY INTO.

   Synthetic data only — the NDJSON payloads are generated by data_generator/,
   contain NO real PHI/PII, and are uploaded via PUT from the operator/CI host.

   WHAT THIS CREATES (in RAW schema)
     - FF_JSON_NDJSON : newline-delimited JSON file format for event feeds.
     - FF_CSV_SEED    : CSV file format for seed/reference loads.
     - One internal named stage per feed:
         STG_CLAIM_EVENT, STG_ELIGIBILITY_EVENT, STG_PROVIDER_EVENT,
         STG_PHARMACY_EVENT, STG_ADJUDICATION_EVENT

   RUN AS: CLAIMS_SYSADMIN. Parameterised on $claims_db (default CLAIMS_DEV).
   IDEMPOTENT: CREATE ... IF NOT EXISTS for stages; CREATE OR REPLACE for file
   formats is safe (no data lives in a file format).
   ============================================================================= */

SET claims_db = 'CLAIMS_DEV';   -- override: -D claims_db=CLAIMS_PROD

USE ROLE CLAIMS_SYSADMIN;
USE DATABASE IDENTIFIER($claims_db);
USE SCHEMA RAW;

/* -----------------------------------------------------------------------------
   1. FILE FORMATS
   -----------------------------------------------------------------------------
   NDJSON (newline-delimited JSON): one JSON object PER LINE. This is the right
   shape for event feeds because each line is an independently parseable record,
   so COPY INTO emits one row per event into a VARIANT column.

   STRIP_OUTER_ARRAY = FALSE : our files are NDJSON, NOT a single big JSON array.
       (Set TRUE only if a feed delivers `[ {...}, {...} ]` as one document.)
   --------------------------------------------------------------------------- */
CREATE OR REPLACE FILE FORMAT FF_JSON_NDJSON
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE          -- NDJSON: one object per line, not an array
  STRIP_NULL_VALUES = FALSE          -- keep nulls; bronze is source-faithful
  IGNORE_UTF8_ERRORS = FALSE
  COMPRESSION = AUTO                 -- transparently handles .gz uploaded by PUT
  COMMENT = 'NDJSON (one JSON object per line) for claims event feeds -> VARIANT payload.';

CREATE OR REPLACE FILE FORMAT FF_CSV_SEED
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE
  COMPRESSION = AUTO
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
  COMMENT = 'CSV format for seed/reference data loads.';

/* -----------------------------------------------------------------------------
   2. INTERNAL NAMED STAGES (one per feed)
   -----------------------------------------------------------------------------
   Internal named stages live inside Snowflake-managed storage. We bind each to
   the NDJSON file format so COPY INTO does not need to restate it. DIRECTORY is
   enabled so we can list/track files (useful for LOAD_BATCH reconciliation).
   One stage per feed keeps file namespaces clean and lets us reason about
   per-feed arrival/late-arrival independently.
   --------------------------------------------------------------------------- */
CREATE STAGE IF NOT EXISTS STG_CLAIM_EVENT
  FILE_FORMAT = FF_JSON_NDJSON
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Internal stage for synthetic CLAIM event NDJSON.';

CREATE STAGE IF NOT EXISTS STG_ELIGIBILITY_EVENT
  FILE_FORMAT = FF_JSON_NDJSON
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Internal stage for synthetic ELIGIBILITY event NDJSON.';

CREATE STAGE IF NOT EXISTS STG_PROVIDER_EVENT
  FILE_FORMAT = FF_JSON_NDJSON
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Internal stage for synthetic PROVIDER event NDJSON.';

CREATE STAGE IF NOT EXISTS STG_PHARMACY_EVENT
  FILE_FORMAT = FF_JSON_NDJSON
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Internal stage for synthetic PHARMACY event NDJSON.';

CREATE STAGE IF NOT EXISTS STG_ADJUDICATION_EVENT
  FILE_FORMAT = FF_JSON_NDJSON
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Internal stage for synthetic ADJUDICATION event NDJSON.';

-- Optional shared stage for CSV seeds (dim reference data).
CREATE STAGE IF NOT EXISTS STG_SEEDS
  FILE_FORMAT = FF_CSV_SEED
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Internal stage for CSV seed/reference uploads.';

/* -----------------------------------------------------------------------------
   3. GRANTS
   -----------------------------------------------------------------------------
   Loader: READ+WRITE on stages (PUT) and USAGE on formats. Transformer/CI: READ
   so dbt/CI can validate or re-COPY if needed.
   --------------------------------------------------------------------------- */
GRANT USAGE ON FILE FORMAT FF_JSON_NDJSON TO ROLE CLAIMS_LOADER;
GRANT USAGE ON FILE FORMAT FF_CSV_SEED    TO ROLE CLAIMS_LOADER;
GRANT USAGE ON FILE FORMAT FF_JSON_NDJSON TO ROLE CLAIMS_TRANSFORMER;
GRANT USAGE ON FILE FORMAT FF_CSV_SEED    TO ROLE CLAIMS_TRANSFORMER;

GRANT READ, WRITE ON STAGE STG_CLAIM_EVENT        TO ROLE CLAIMS_LOADER;
GRANT READ, WRITE ON STAGE STG_ELIGIBILITY_EVENT  TO ROLE CLAIMS_LOADER;
GRANT READ, WRITE ON STAGE STG_PROVIDER_EVENT     TO ROLE CLAIMS_LOADER;
GRANT READ, WRITE ON STAGE STG_PHARMACY_EVENT     TO ROLE CLAIMS_LOADER;
GRANT READ, WRITE ON STAGE STG_ADJUDICATION_EVENT TO ROLE CLAIMS_LOADER;
GRANT READ, WRITE ON STAGE STG_SEEDS              TO ROLE CLAIMS_LOADER;

GRANT READ ON STAGE STG_CLAIM_EVENT        TO ROLE CLAIMS_TRANSFORMER;
GRANT READ ON STAGE STG_ELIGIBILITY_EVENT  TO ROLE CLAIMS_TRANSFORMER;
GRANT READ ON STAGE STG_PROVIDER_EVENT     TO ROLE CLAIMS_TRANSFORMER;
GRANT READ ON STAGE STG_PHARMACY_EVENT     TO ROLE CLAIMS_TRANSFORMER;
GRANT READ ON STAGE STG_ADJUDICATION_EVENT TO ROLE CLAIMS_TRANSFORMER;

-- CI loads synthetic fixtures during integration tests.
GRANT READ, WRITE ON STAGE STG_CLAIM_EVENT        TO ROLE CLAIMS_CI;
GRANT READ, WRITE ON STAGE STG_ELIGIBILITY_EVENT  TO ROLE CLAIMS_CI;
GRANT READ, WRITE ON STAGE STG_PROVIDER_EVENT     TO ROLE CLAIMS_CI;
GRANT READ, WRITE ON STAGE STG_PHARMACY_EVENT     TO ROLE CLAIMS_CI;
GRANT READ, WRITE ON STAGE STG_ADJUDICATION_EVENT TO ROLE CLAIMS_CI;

/* =============================================================================
   EXAMPLE: PUT (upload) + COPY INTO (load) — run after 006 creates BR_RAW_*.
   -----------------------------------------------------------------------------
   These are illustrative; the loader pipeline (or CI) issues them per batch.

   -- 1) Upload synthetic NDJSON from the local generator output to the stage.
   --    AUTO_COMPRESS gzips on the wire; FF COMPRESSION=AUTO handles it on load.
   --    (PUT must be run from SnowSQL / a driver, not the Snowsight worksheet.)
   --
   --    PUT file:///abs/path/data_generator/out/claim_events_*.ndjson
   --        @CLAIMS_DEV.RAW.STG_CLAIM_EVENT
   --        AUTO_COMPRESS = TRUE
   --        PARALLEL = 8;

   -- 2) Inspect what landed on the stage (directory table is enabled):
   --    LIST @CLAIMS_DEV.RAW.STG_CLAIM_EVENT;

   -- 3) COPY INTO the bronze landing table. We project stage metadata
   --    (METADATA$FILENAME, METADATA$FILE_ROW_NUMBER) into provenance columns
   --    and keep the full event as VARIANT payload (bronze = source-faithful).
   --
   --    COPY INTO CLAIMS_DEV.BRONZE.BR_RAW_CLAIM_EVENT
   --      ( bronze_event_id, source_system, source_file_name,
   --        source_file_row_number, source_extract_ts, event_type,
   --        business_event_ts, natural_key, payload, payload_hash,
   --        record_status, batch_id, load_id, pipeline_run_id, is_reprocessed )
   --    FROM (
   --      SELECT
   --        MD5(METADATA$FILENAME || ':' || METADATA$FILE_ROW_NUMBER) AS bronze_event_id,
   --        $1:source_system::string                                  AS source_system,
   --        METADATA$FILENAME                                         AS source_file_name,
   --        METADATA$FILE_ROW_NUMBER                                  AS source_file_row_number,
   --        $1:extract_ts::timestamp_ntz                              AS source_extract_ts,
   --        $1:event_type::string                                     AS event_type,
   --        $1:event_ts::timestamp_ntz                                AS business_event_ts,
   --        $1:claim_id::string                                       AS natural_key,
   --        $1                                                        AS payload,
   --        MD5(TO_VARCHAR($1))                                       AS payload_hash,
   --        'LANDED'                                                  AS record_status,
   --        '<BATCH_ID>'                                              AS batch_id,
   --        '<LOAD_ID>'                                               AS load_id,
   --        '<PIPELINE_RUN_ID>'                                       AS pipeline_run_id,
   --        FALSE                                                     AS is_reprocessed
   --      FROM @CLAIMS_DEV.RAW.STG_CLAIM_EVENT
   --    )
   --    FILE_FORMAT = (FORMAT_NAME = CLAIMS_DEV.RAW.FF_JSON_NDJSON)
   --    ON_ERROR = 'CONTINUE'         -- malformed rows -> quarantine reconcile
   --    PURGE = FALSE;                -- keep staged files for audit/reprocessing

   -- 4) Record the batch outcome in CONTROL.LOAD_BATCH (see script 005).
   ============================================================================= */

/* DONE. */
