#!/usr/bin/env python3
"""synthea_to_x12.py -- convert Synthea CSV output into X12 837P (Professional
health-care claim) EDI files.

  ##################################################################
  #  SYNTHETIC DATA -- NOT REAL CMS / MEDICARE / MEDICAID / PHI.    #
  #  All input is generated by Synthea (synthetichealth/synthea),  #
  #  a synthetic patient generator. The X12 produced here uses      #
  #  clearly-fake NPIs (10 digits starting with 9), synthetic       #
  #  payer/member ids, and must NOT be submitted to any real        #
  #  clearinghouse or payer.                                        #
  ##################################################################

The output mirrors the segment structure/order of x12/sample_837p.txt, which is
the shape the project's moov-io/x12 (rule_5010_837p) parser expects. The
companion Go tool (x12/x12tojson --rule 837p) must parse every file we emit.

X12 delimiters used (matching the project's parser, see x12/main.go):
  element separator      = '*'
  segment terminator     = '~'  (each segment also on its own line)
  component / sub-element = '<'  (NOT ':' -- this is ISA16 in the sample)
  repetition             = '^'

Pipeline context:
  Synthea CSV -> [this script] -> X12 837P -> Snowflake bronze (raw text)
              -> Airflow + moov-io/x12 (x12tojson) -> JSON bronze -> dbt canonical

One subscriber HL loop is emitted per CLAIM (a row in claims.csv that has at
least one TYPE='CHARGE' service line in claims_transactions.csv). Claims are
batched into interchanges of --claims-per-file claims each, one ISA/GS/ST per
file. The run is deterministic: same CSVs + same --seed => byte-identical X12.

Pure standard library only (csv, argparse, datetime, os, pathlib, hashlib).
"""

import argparse
import csv
import datetime as _dt
import hashlib
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# X12 delimiters (see module docstring / x12/main.go).
# ---------------------------------------------------------------------------
ELEM = "*"   # element separator
SEG = "~"    # segment terminator
COMP = "<"   # component (sub-element) separator
REP = "^"    # repetition separator

# Fixed synthetic interchange identifiers. These are obviously-fake placeholder
# trading-partner ids; they are NOT real CMS submitter/receiver ids.
SUBMITTER_ID = "999000001"          # synthetic submitter (ISA/GS sender, NM1*41)
RECEIVER_ID = "999000002"           # synthetic receiver (ISA/GS receiver, NM1*40)
SUBMITTER_NAME = "SYNTHEA SUBMITTER"
RECEIVER_NAME = "SYNTHEA RECEIVER"
SUBMITTER_CONTACT = "SYNTHEA DATA OPS"
SUBMITTER_PHONE = "9995550100"

# Fallback billing organization, used when a claim's provider/organization can
# not be resolved from providers.csv / organizations.csv.
FALLBACK_BILLING_NAME = "SYNTHEA BILLING ORG"
FALLBACK_ADDR = "1 SYNTHETIC WAY"
FALLBACK_CITY = "SPRINGFIELD"
FALLBACK_STATE = "MA"
FALLBACK_ZIP = "01101"


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------
def _clean(s):
    """Uppercase + strip X12 delimiter characters out of free text so we never
    accidentally inject a separator into an element value."""
    if s is None:
        return ""
    s = str(s)
    for ch in (ELEM, SEG, COMP, REP):
        s = s.replace(ch, " ")
    return s.strip().upper()


def _digits(s):
    """Keep only digits (used for zips, phones)."""
    return "".join(c for c in str(s or "") if c.isdigit())


def _zip(s):
    """Normalize a zip to 5 or 9 digits (X12 N403 wants no dash)."""
    z = _digits(s)
    return z if z else "00000"


def _ymd(s):
    """Convert a Synthea date/datetime string to YYYYMMDD. Synthea emits either
    'YYYY-MM-DD' or 'YYYY-MM-DDThh:mm:ssZ'. Returns '' if unparseable."""
    if not s:
        return ""
    s = str(s).strip()
    for fmt in ("%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d"):
        try:
            return _dt.datetime.strptime(s, fmt).strftime("%Y%m%d")
        except ValueError:
            continue
    # Last-ditch: take the leading date portion and remove separators.
    head = s[:10].replace("-", "")
    return head if head.isdigit() and len(head) == 8 else ""


def _gender(g):
    """Map Synthea GENDER (M/F) to the X12 DMG03 / NM1 gender code (M/F/U)."""
    g = (g or "").strip().upper()
    return g if g in ("M", "F") else "U"


def _icd(code):
    """Diagnosis code for HI: strip a decimal point (ICD-10 dotted form) and any
    X12 delimiters. Synthea here emits SNOMED numeric codes, which pass through
    unchanged; this also handles dotted ICD-10 should the source change."""
    return _clean((code or "").replace(".", ""))


def _money(s):
    """Normalize a monetary amount string. Returns '' for blank/zero-length."""
    s = (s or "").strip()
    return s if s else "0"


def synthetic_npi(seed):
    """Deterministically derive a clearly-synthetic 10-digit NPI that starts
    with '9' (the 9xx-prefix range is not issued by NPPES, so these can never
    collide with a real NPI). Derived from a stable hash of `seed`."""
    h = hashlib.sha256(str(seed).encode("utf-8")).hexdigest()
    n = int(h[:12], 16) % 1_000_000_000  # 9 digits of entropy
    return "9" + str(n).zfill(9)


def synthetic_id(prefix, seed, length=8):
    """Deterministic synthetic identifier (member id, payer id, etc.)."""
    h = hashlib.sha256((prefix + "|" + str(seed)).encode("utf-8")).hexdigest()
    return (prefix + h.upper())[:length]


# ---------------------------------------------------------------------------
# CSV loading
# ---------------------------------------------------------------------------
def load_csv(path):
    """Load a CSV into a list of dict rows (stdlib csv.DictReader)."""
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def index_by(rows, key):
    """Index a list of rows by `key` (first row wins on duplicate keys)."""
    out = {}
    for r in rows:
        k = r.get(key)
        if k and k not in out:
            out[k] = r
    return out


# ---------------------------------------------------------------------------
# Segment builder
# ---------------------------------------------------------------------------
class SegmentWriter:
    """Accumulates X12 segments (as strings) and tracks a count from ST..SE."""

    def __init__(self):
        self.lines = []

    def seg(self, *elements):
        """Append one segment. Trailing empty elements are trimmed (X12 allows
        omitting trailing empties), but we keep the exact shape of the sample by
        only trimming purely-empty tails."""
        # Build raw element list, dropping trailing empties.
        elems = [("" if e is None else str(e)) for e in elements]
        while len(elems) > 1 and elems[-1] == "":
            elems.pop()
        self.lines.append(ELEM.join(elems) + SEG)

    def comp(self, *parts):
        """Join sub-elements with the component separator '<'."""
        return COMP.join("" if p is None else str(p) for p in parts)

    def __len__(self):
        return len(self.lines)


# ---------------------------------------------------------------------------
# Core 837P assembly
# ---------------------------------------------------------------------------
def diagnoses_for_claim(claim):
    """Return distinct, cleaned diagnosis codes from claims.DIAGNOSIS1..8 in
    order (first becomes the principal BK code, the rest BF)."""
    codes = []
    for i in range(1, 9):
        c = _icd(claim.get(f"DIAGNOSIS{i}", ""))
        if c and c not in codes:
            codes.append(c)
    return codes[:12]  # HI supports up to 12 diagnosis components


def build_hi(sw, codes):
    """Build the HI (health-care diagnosis) segment: first code BK (principal),
    remaining codes BF, ICD/SNOMED code in the component after the qualifier."""
    if not codes:
        return
    parts = [sw.comp("BK", codes[0])]
    for c in codes[1:]:
        parts.append(sw.comp("BF", c))
    sw.seg("HI", *parts)


def build_interchange(claims_batch, ctx, isa_ctrl, gs_ctrl, st_ctrl):
    """Build a complete ISA..IEA interchange string for one batch of claims.

    `claims_batch` is a list of dicts produced by collect_claims(). Returns
    (text, segment_count_ST_to_SE_inclusive, n_service_lines)."""
    sw = SegmentWriter()
    now = ctx["now"]
    date8 = now.strftime("%Y%m%d")
    date6 = now.strftime("%y%m%d")
    time4 = now.strftime("%H%M")
    time_hms = now.strftime("%H%M%S")

    # ----- ISA: fixed-width-ish header. Component sep is the LAST element. -----
    sw.seg(
        "ISA", "00", " " * 10, "00", " " * 10,
        "ZZ", SUBMITTER_ID.ljust(15), "ZZ", RECEIVER_ID.ljust(15),
        date6, time4, REP, "00501",
        str(isa_ctrl).zfill(9), "0", "P", COMP,
    )
    # ----- GS: functional group header (HC = health-care claim) -----
    sw.seg("GS", "HC", SUBMITTER_ID, RECEIVER_ID, date8, time_hms,
           str(gs_ctrl), "X", "005010X222A1")

    # ===== ST: transaction set header (start of SE counting) =====
    st_index = len(sw)
    sw.seg("ST", "837", str(st_ctrl).zfill(9), "005010X222A1")
    sw.seg("BHT", "0019", "00", str(st_ctrl).zfill(9), date8, time_hms, "CH")

    # 1000A submitter
    sw.seg("NM1", "41", "2", SUBMITTER_NAME, "", "", "", "", "46", SUBMITTER_ID)
    sw.seg("PER", "IC", SUBMITTER_CONTACT, "TE", SUBMITTER_PHONE)
    # 1000B receiver
    sw.seg("NM1", "40", "2", RECEIVER_NAME, "", "", "", "", "46", RECEIVER_ID)

    # ----- 2000A billing provider (shared, claim_seq 0) -----
    bp = ctx["billing"]
    sw.seg("HL", "1", "", "20", "1")
    sw.seg("NM1", "85", "2", bp["name"], "", "", "", "", "XX", bp["npi"])
    sw.seg("N3", bp["addr"])
    sw.seg("N4", bp["city"], bp["state"], bp["zip"])
    sw.seg("REF", "EI", bp["tax_id"])

    n_lines = 0
    hl_counter = 1  # billing provider was HL 1; subscriber HLs follow.

    for claim in claims_batch:
        hl_counter += 1
        # ----- 2000B subscriber HL (HL03=22 marks a new claim) -----
        sw.seg("HL", str(hl_counter), "1", "22", "0")
        sw.seg("SBR", "P", "18", "", "", "", "", "", "", "CI")

        # 2010BA subscriber name + address + demographics
        pat = claim["patient"]
        sw.seg("NM1", "IL", "1", pat["last"], pat["first"], "", "", "",
               "MI", pat["member_id"])
        sw.seg("N3", pat["addr"])
        sw.seg("N4", pat["city"], pat["state"], pat["zip"])
        sw.seg("DMG", "D8", pat["birth"], pat["gender"])

        # 2010BB payer
        pay = claim["payer"]
        sw.seg("NM1", "PR", "2", pay["name"], "", "", "", "", "PI", pay["id"])
        sw.seg("N3", pay["addr"])
        sw.seg("N4", pay["city"], pay["state"], pay["zip"])

        # ----- 2300 claim -----
        # CLM05 = facility code value composite: <POS><B<1
        clm05 = sw.comp(claim["pos"], "B", "1")
        sw.seg("CLM", claim["claim_id"], claim["total_charge"], "", "",
               clm05, "Y", "A", "Y", "Y")

        # HI diagnoses
        build_hi(sw, claim["diagnoses"])

        # 2310B rendering provider
        rp = claim["rendering"]
        sw.seg("NM1", "82", "2", rp["name"], "", "", "", "", "XX", rp["npi"])

        # ----- 2400 service lines -----
        for idx, line in enumerate(claim["lines"], start=1):
            sw.seg("LX", str(idx))
            sv101 = sw.comp("HC", line["proc"])
            sw.seg("SV1", sv101, line["charge"], "UN", line["units"],
                   "", "", "1")
            if line["date"]:
                sw.seg("DTP", "472", "D8", line["date"])
            n_lines += 1

    # ===== SE: count segments from ST..SE inclusive =====
    seg_count = (len(sw) - st_index) + 1  # +1 for the SE segment itself
    sw.seg("SE", str(seg_count), str(st_ctrl).zfill(9))
    sw.seg("GE", "1", str(gs_ctrl))
    sw.seg("IEA", "1", str(isa_ctrl).zfill(9))

    return "\n".join(sw.lines) + "\n", seg_count, n_lines


# ---------------------------------------------------------------------------
# Claim collection (joins the CSVs into the structures build_interchange wants)
# ---------------------------------------------------------------------------
def collect_claims(csv_dir, max_claims, seed):
    """Read the Synthea CSVs and assemble a list of claim dicts, limited to
    claims that have >=1 TYPE='CHARGE' service line. Returns
    (claims_list, total_claims_seen, billing_ctx)."""
    csv_dir = Path(csv_dir)

    claims = load_csv(csv_dir / "claims.csv")
    patients = index_by(load_csv(csv_dir / "patients.csv"), "Id")
    providers = index_by(load_csv(csv_dir / "providers.csv"), "Id")
    organizations = index_by(load_csv(csv_dir / "organizations.csv"), "Id")
    payers = index_by(load_csv(csv_dir / "payers.csv"), "Id")

    # Group TYPE='CHARGE' transaction rows by CLAIMID, preserving file order.
    charges_by_claim = {}
    with open(csv_dir / "claims_transactions.csv", newline="",
              encoding="utf-8") as fh:
        for tx in csv.DictReader(fh):
            if (tx.get("TYPE") or "").strip().upper() != "CHARGE":
                continue
            cid = tx.get("CLAIMID")
            if cid:
                charges_by_claim.setdefault(cid, []).append(tx)

    # Build a shared synthetic billing organization. We use the first claim's
    # provider->organization if resolvable, else a fixed synthetic org. (Per
    # spec the billing provider is rendered once as HL*1 per interchange.)
    billing = _resolve_billing(claims, providers, organizations, seed)

    out = []
    total_seen = 0
    for claim in claims:
        total_seen += 1
        cid = claim.get("Id")
        lines = charges_by_claim.get(cid)
        if not lines:
            continue  # skip claims with no CHARGE service lines

        pat_row = patients.get(claim.get("PATIENTID"), {})
        member_id = synthetic_id("M", claim.get("PATIENTID", cid))
        patient = {
            "last": _clean(pat_row.get("LAST")) or "DOE",
            "first": _clean(pat_row.get("FIRST")) or "PATIENT",
            "member_id": member_id,
            "addr": _clean(pat_row.get("ADDRESS")) or FALLBACK_ADDR,
            "city": _clean(pat_row.get("CITY")) or FALLBACK_CITY,
            "state": _state_abbr(pat_row.get("STATE")) or FALLBACK_STATE,
            "zip": _zip(pat_row.get("ZIP")),
            "birth": _ymd(pat_row.get("BIRTHDATE")) or "19000101",
            "gender": _gender(pat_row.get("GENDER")),
        }

        pay_row = payers.get(claim.get("PRIMARYPATIENTINSURANCEID"), {})
        payer = {
            "name": _clean(pay_row.get("NAME")) or "SYNTHETIC PAYER",
            "id": synthetic_id("P", claim.get("PRIMARYPATIENTINSURANCEID") or cid),
            "addr": _clean(pay_row.get("ADDRESS")) or FALLBACK_ADDR,
            "city": _clean(pay_row.get("CITY")) or FALLBACK_CITY,
            "state": _state_abbr(pay_row.get("STATE_HEADQUARTERED")) or FALLBACK_STATE,
            "zip": _zip(pay_row.get("ZIP")) if _digits(pay_row.get("ZIP")) else FALLBACK_ZIP,
        }

        prov_row = providers.get(claim.get("PROVIDERID"), {})
        rendering = {
            "name": _clean(prov_row.get("NAME")) or billing["name"],
            "npi": synthetic_npi("rendering|" + (claim.get("PROVIDERID") or cid)),
        }

        # POS: claims_transactions.PLACEOFSERVICE is a Synthea UUID, not a CMS
        # place-of-service code, so default to 11 (office). Use the first line's
        # value only if it happens to be a numeric POS code.
        pos = "11"
        first_pos = (lines[0].get("PLACEOFSERVICE") or "").strip()
        if first_pos.isdigit() and len(first_pos) <= 2:
            pos = first_pos

        # Service lines + total charge.
        svc_lines = []
        total = 0.0
        for ln in lines:
            amount = (ln.get("AMOUNT") or "").strip()
            if not amount:
                # Fall back to UNITAMOUNT * UNITS.
                ua = (ln.get("UNITAMOUNT") or "0").strip() or "0"
                un = (ln.get("UNITS") or "1").strip() or "1"
                try:
                    amount = f"{float(ua) * float(un):.2f}"
                except ValueError:
                    amount = "0"
            try:
                total += float(amount)
            except ValueError:
                pass
            units = (ln.get("UNITS") or "1").strip() or "1"
            # SV104 (units) must be numeric; coerce non-numeric to 1.
            try:
                float(units)
            except ValueError:
                units = "1"
            svc_lines.append({
                "proc": _clean(ln.get("PROCEDURECODE")) or "99213",
                "charge": _money(amount),
                "units": units,
                "date": _ymd(ln.get("FROMDATE")),
            })

        diagnoses = diagnoses_for_claim(claim)
        if not diagnoses:
            diagnoses = ["Z000"]  # synthetic placeholder principal diagnosis

        out.append({
            "claim_id": _clean(cid)[:38] or cid,
            "total_charge": f"{total:.2f}",
            "pos": pos,
            "patient": patient,
            "payer": payer,
            "rendering": rendering,
            "diagnoses": diagnoses,
            "lines": svc_lines,
        })

        if max_claims and len(out) >= max_claims:
            break

    return out, total_seen, billing


def _state_abbr(state):
    """Map a Synthea full state name (e.g. 'Massachusetts') to a 2-letter USPS
    abbreviation. Falls back to the first 2 letters uppercased."""
    s = (state or "").strip()
    if not s:
        return ""
    if len(s) == 2:
        return s.upper()
    table = {
        "ALABAMA": "AL", "ALASKA": "AK", "ARIZONA": "AZ", "ARKANSAS": "AR",
        "CALIFORNIA": "CA", "COLORADO": "CO", "CONNECTICUT": "CT",
        "DELAWARE": "DE", "FLORIDA": "FL", "GEORGIA": "GA", "HAWAII": "HI",
        "IDAHO": "ID", "ILLINOIS": "IL", "INDIANA": "IN", "IOWA": "IA",
        "KANSAS": "KS", "KENTUCKY": "KY", "LOUISIANA": "LA", "MAINE": "ME",
        "MARYLAND": "MD", "MASSACHUSETTS": "MA", "MICHIGAN": "MI",
        "MINNESOTA": "MN", "MISSISSIPPI": "MS", "MISSOURI": "MO",
        "MONTANA": "MT", "NEBRASKA": "NE", "NEVADA": "NV",
        "NEW HAMPSHIRE": "NH", "NEW JERSEY": "NJ", "NEW MEXICO": "NM",
        "NEW YORK": "NY", "NORTH CAROLINA": "NC", "NORTH DAKOTA": "ND",
        "OHIO": "OH", "OKLAHOMA": "OK", "OREGON": "OR", "PENNSYLVANIA": "PA",
        "RHODE ISLAND": "RI", "SOUTH CAROLINA": "SC", "SOUTH DAKOTA": "SD",
        "TENNESSEE": "TN", "TEXAS": "TX", "UTAH": "UT", "VERMONT": "VT",
        "VIRGINIA": "VA", "WASHINGTON": "WA", "WEST VIRGINIA": "WV",
        "WISCONSIN": "WI", "WYOMING": "WY",
        "DISTRICT OF COLUMBIA": "DC",
    }
    return table.get(s.upper(), s[:2].upper())


def _resolve_billing(claims, providers, organizations, seed):
    """Resolve a single billing organization (NM1*85) for the interchange.
    Uses the first claim's provider -> organization if resolvable, else a fixed
    synthetic org."""
    name = FALLBACK_BILLING_NAME
    addr, city, state, zipc = FALLBACK_ADDR, FALLBACK_CITY, FALLBACK_STATE, FALLBACK_ZIP
    org_id = "synthetic-org"

    for claim in claims:
        prov = providers.get(claim.get("PROVIDERID"))
        if not prov:
            continue
        org = organizations.get(prov.get("ORGANIZATION"))
        if not org:
            continue
        name = _clean(org.get("NAME")) or FALLBACK_BILLING_NAME
        addr = _clean(org.get("ADDRESS")) or FALLBACK_ADDR
        city = _clean(org.get("CITY")) or FALLBACK_CITY
        state = _state_abbr(org.get("STATE")) or FALLBACK_STATE
        zipc = _zip(org.get("ZIP"))
        org_id = org.get("Id") or org_id
        break

    return {
        "name": name,
        "addr": addr,
        "city": city,
        "state": state,
        "zip": zipc,
        "npi": synthetic_npi("billing|" + str(org_id)),
        "tax_id": synthetic_id("9", "tax|" + str(org_id), length=9),
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main(argv=None):
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Convert Synthea CSV output into X12 837P EDI files "
                    "(SYNTHETIC data -- not real CMS/PHI).")
    parser.add_argument("--csv-dir", default=str(here / "output" / "csv"),
                        help="directory containing Synthea CSV files "
                             "(default: output/csv)")
    parser.add_argument("--out-dir", default=str(here / "output" / "x12"),
                        help="directory to write .x12 files "
                             "(default: output/x12)")
    parser.add_argument("--claims-per-file", type=int, default=50,
                        help="claims (subscriber HL loops) per interchange file "
                             "(default: 50)")
    parser.add_argument("--max-claims", type=int, default=300,
                        help="cap on total claims processed (default: 300). "
                             "Capping is reported, never silent.")
    parser.add_argument("--seed", default="42",
                        help="seed for deterministic synthetic ids/NPIs "
                             "(default: 42)")
    args = parser.parse_args(argv)

    # Deterministic timestamp derived from the seed (so reruns are identical).
    h = int(hashlib.sha256(str(args.seed).encode()).hexdigest()[:8], 16)
    base = _dt.datetime(2020, 1, 1) + _dt.timedelta(seconds=h % 86400)
    ctx = {"now": base}

    csv_dir = Path(args.csv_dir)
    if not (csv_dir / "claims.csv").exists():
        sys.stderr.write(f"ERROR: no claims.csv found in {csv_dir}\n")
        return 2

    claims, total_seen, billing = collect_claims(csv_dir, args.max_claims, args.seed)
    ctx["billing"] = billing

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    files_written = 0
    lines_written = 0
    claims_written = 0
    per_file = max(1, args.claims_per_file)

    for batch_no, start in enumerate(range(0, len(claims), per_file), start=1):
        batch = claims[start:start + per_file]
        # Distinct, consistent control numbers per interchange.
        isa_ctrl = batch_no
        gs_ctrl = 1000 + batch_no
        st_ctrl = batch_no
        text, _seg_count, n_lines = build_interchange(
            batch, ctx, isa_ctrl, gs_ctrl, st_ctrl)
        fname = out_dir / f"claims_837p_{batch_no:04d}.x12"
        fname.write_text(text, encoding="utf-8")
        files_written += 1
        lines_written += n_lines
        claims_written += len(batch)

    # ---- summary ----
    print("=" * 64)
    print(" Synthea -> X12 837P conversion  (SYNTHETIC DATA, NOT REAL PHI)")
    print("=" * 64)
    print(f"  claims read (claims.csv rows)        : {total_seen}")
    print(f"  claims with >=1 CHARGE line          : {len(claims) if args.max_claims == 0 or len(claims) < args.max_claims else '>= ' + str(len(claims))}")
    print(f"  claims written to X12                : {claims_written}")
    print(f"  service lines (LX/SV1/DTP) written   : {lines_written}")
    print(f"  interchange files written            : {files_written}")
    print(f"  output directory                     : {out_dir}")
    if total_seen > args.max_claims > 0 and claims_written >= args.max_claims:
        print(f"  NOTE: capped at --max-claims={args.max_claims}. "
              f"Re-run with a higher --max-claims to emit more (no silent truncation).")
    print("=" * 64)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
